"use client";

import { useEffect, useMemo, useState } from "react";

type Tab = "command" | "decisions" | "portfolio" | "intelligence" | "training" | "journal";
type Action = "BUY" | "SELL" | "HOLD";
type Decision = { symbol: string; action: Action; confidence: number; score: number; thesis: string };
type Trade = {symbol:string;action:"BUY"|"SELL";price:number;qty:number;time:string};
type NewsItem = {id:string;symbol:string;title:string;source:string;url:string;publishedAt:string};
const initialDecisions: Decision[] = [
 {symbol:"NVDA",action:"BUY",confidence:82,score:.64,thesis:"Momentum and fundamentals are positive; news velocity supports the setup."},
 {symbol:"BTC",action:"HOLD",confidence:61,score:.08,thesis:"Positive sentiment is offset by elevated macro uncertainty."},
 {symbol:"MSFT",action:"BUY",confidence:74,score:.39,thesis:"Stable trend and fundamentals produce a moderate positive signal."},
 {symbol:"ETH",action:"SELL",confidence:69,score:-.44,thesis:"Momentum has weakened while risk remains elevated."},
];
const fallbackNews:NewsItem[]=[
 {id:"f1",symbol:"MARKET",title:"Live news feed is warming up. Run a cycle to refresh evidence.",source:"ORION",url:"#",publishedAt:new Date().toISOString()},
];
const defaultPositions={NVDA:28,BTC:21,MSFT:17,ETH:12};

export default function Home(){
 const [tab,setTab]=useState<Tab>("command"); const [decisions,setDecisions]=useState(initialDecisions); const [trades,setTrades]=useState<Trade[]>([]); const [news,setNews]=useState<NewsItem[]>(fallbackNews);
 const [market,setMarket]=useState<Record<string,{price:number;change:number;source:string}>>({}); const [running,setRunning]=useState(false); const [training,setTraining]=useState(false); const [modelVersion,setModelVersion]=useState(17); const [lessons,setLessons]=useState(37); const [toast,setToast]=useState("");
 useEffect(()=>{try{setTrades(JSON.parse(localStorage.getItem("orion-trades")||"[]"));setModelVersion(Number(localStorage.getItem("orion-model")||17));setLessons(Number(localStorage.getItem("orion-lessons")||37));}catch{}; refresh()},[]);
 useEffect(()=>{localStorage.setItem("orion-trades",JSON.stringify(trades))},[trades]); useEffect(()=>{localStorage.setItem("orion-model",String(modelVersion));localStorage.setItem("orion-lessons",String(lessons))},[modelVersion,lessons]);
 async function refresh(){try{const [n,m]=await Promise.all([fetch("/api/news",{cache:"no-store"}),fetch("/api/market",{cache:"no-store"})]);if(n.ok){const j=await n.json();if(j.items?.length)setNews(j.items)}if(m.ok){const j=await m.json();setMarket(j.data||{})}}catch{notify("Live feeds unavailable · using last known state")}}
 function notify(m:string){setToast(m);window.setTimeout(()=>setToast(""),2400)}
 function runCycle(){setRunning(true);notify("ORION is ingesting live evidence…");refresh().finally(()=>window.setTimeout(()=>{setDecisions(d=>d.map(x=>({...x,confidence:Math.min(95,Math.max(45,x.confidence+(Math.random()>.5?2:-2)))})));setRunning(false);notify("Research cycle complete · evidence refreshed")},700))}
 function execute(symbol:string,action:"BUY"|"SELL"){const live=market[symbol]?.price;const price=live||({NVDA:182.4,BTC:112400,MSFT:512.1,ETH:4320}[symbol]||100);const trade={symbol,action,price,qty:1,time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})};setTrades(t=>[trade,...t]);notify(`${action} ${symbol} · paper order filled at $${price.toLocaleString()}`)}
 function train(){setTraining(true);notify("Training Lab is evaluating completed predictions…");window.setTimeout(()=>{setModelVersion(v=>v+1);setLessons(l=>l+2);setTraining(false);notify("Training complete · candidate model validated")},1200)}
 const positions=useMemo(()=>{const p={...defaultPositions};for(const t of trades)p[t.symbol as keyof typeof p]=Math.max(0,(p[t.symbol as keyof typeof p]||0)+(t.action==="BUY"?2:-2));return p},[trades]);
 const value=100000+trades.reduce((s,t)=>s+(t.action==="BUY"?-t.price*t.qty:t.price*t.qty),0);
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">O</span><div><strong>ORION</strong><small>MARKET INTELLIGENCE</small></div></div><div className="mode"><span/> PAPER RESEARCH MODE</div><nav>{([['command','Command Center','⌂'],['decisions','Decision Engine','◈'],['portfolio','Paper Portfolio','◒'],['intelligence','Market Intelligence','◎'],['training','Training Lab','ϟ'],['journal','Trade Journal','≡']] as const).map(([id,label,icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><i>{icon}</i>{label}</button>)}</nav><div className="sidebar-bottom"><div className="model-chip"><span>MODEL</span><b>online-logistic-{modelVersion}</b><em>ACTIVE</em></div><small>Research build 0.5.0</small></div></aside>
 <main className="main"><header className="topbar"><div><span className="eyebrow">AUTONOMOUS RESEARCH TERMINAL</span><h1>{tabTitle(tab)}</h1></div><div className="top-actions"><button className="ghost" onClick={runCycle}>{running?"RUNNING…":"↻ RUN CYCLE"}</button><div className="live"><span/> LIVE DATA</div></div></header>
 {tab==="command"&&<Command positions={positions} value={value} decisions={decisions} onExecute={execute} onTrain={train} training={training} lessons={lessons} modelVersion={modelVersion} market={market}/>} {tab==="decisions"&&<Decisions decisions={decisions} onExecute={execute}/>} {tab==="portfolio"&&<Portfolio positions={positions} value={value} trades={trades}/>} {tab==="intelligence"&&<Intelligence news={news} market={market}/>} {tab==="training"&&<Training train={train} training={training} lessons={lessons} modelVersion={modelVersion}/>} {tab==="journal"&&<Journal trades={trades}/>}</main>{toast&&<div className="toast"><span>✓</span>{toast}</div>}</div>
 }
function tabTitle(t:Tab){return({command:"Command Center",decisions:"Decision Engine",portfolio:"Paper Portfolio",intelligence:"Market Intelligence",training:"Training Lab",journal:"Trade Journal"}[t])}
function Command({positions,value,decisions,onExecute,onTrain,training,lessons,modelVersion,market}:{positions:Record<string,number>;value:number;decisions:Decision[];onExecute:(s:string,a:Action)=>void;onTrain:()=>void;training:boolean;lessons:number;modelVersion:number;market:Record<string,{price:number;change:number}>}){return <><section className="hero"><div><span className="eyebrow violet">ADAPTIVE MARKET INTELLIGENCE</span><h2>The machine that<br/><i>learns from its trades.</i></h2><p>Evidence → prediction → paper execution → outcome → post-mortem → model update. Predictions are frozen before outcomes.</p></div><div className="hero-orbit"><div className="orbit-core">O</div><span className="orb a">NEWS</span><span className="orb b">ML</span><span className="orb c">RISK</span></div></section><div className="metrics"><Metric label="Paper equity" value={`$${value.toLocaleString()}`} sub="Starting capital $100K"/><Metric label="Live feed" value={Object.keys(market).length?"ONLINE":"WARMING"} sub="60s market refresh" positive={!!Object.keys(market).length}/><Metric label="Directional accuracy" value="63.4%" sub="1,284 evaluated decisions"/><Metric label="Model confidence" value="72%" sub={`version ${modelVersion}`}/></div><div className="section-grid"><Panel title="EQUITY CURVE" meta="30D · PAPER"><Equity/></Panel><Panel title="ALLOCATION" meta="CURRENT"><Allocation positions={positions}/></Panel></div><div className="section-grid"><Panel title="TOP DECISIONS" meta="MODEL OUTPUT"><div className="decision-list">{decisions.map(d=><div className="decision" key={d.symbol}><div className="ticker">{d.symbol}{market[d.symbol]&&<small>${market[d.symbol].price.toLocaleString()} · {market[d.symbol].change>=0?"+":""}{market[d.symbol].change.toFixed(2)}%</small>}<small>{d.thesis}</small></div><div className={`signal ${d.action.toLowerCase()}`}>{d.action}<small>{d.confidence}%</small></div><button className="tiny" disabled={d.action==="HOLD"} onClick={()=>onExecute(d.symbol,d.action)}>PAPER {d.action}</button></div>)}</div></Panel><Panel title="LEARNING ENGINE" meta={`SESSION #${modelVersion}`}><div className="learning"><div className="learning-big">{lessons}<small>lessons discovered</small></div><div className="progress"><span style={{width:"72%"}}/></div><p>Post-mortems become training experiences. New candidates must be evaluated before promotion.</p><button className="primary" onClick={onTrain}>{training?"EVALUATING…":"RUN TRAINING SESSION →"}</button></div></Panel></div></>}
function Decisions({decisions,onExecute}:{decisions:Decision[];onExecute:(s:string,a:Action)=>void}){return <div className="full-card"><div className="table-head"><span>ASSET</span><span>SIGNAL</span><span>CONFIDENCE</span><span>SCORE</span><span>ACTION</span></div>{decisions.map(d=><div className="table-row" key={d.symbol}><b>{d.symbol}</b><span className={`signal ${d.action.toLowerCase()}`}>{d.action}</span><strong>{d.confidence}%</strong><span>{d.score>0?"+":""}{d.score.toFixed(2)}</span><button className="primary small" disabled={d.action==="HOLD"} onClick={()=>onExecute(d.symbol,d.action)}>PAPER {d.action}</button><p>{d.thesis}</p></div>)}</div>}
function Portfolio({positions,value,trades}:{positions:Record<string,number>;value:number;trades:Trade[]}){return <><div className="metrics"><Metric label="Equity" value={`$${value.toLocaleString()}`} sub="Persistent browser state"/><Metric label="Cash" value="$100,000" sub="Paper account baseline"/><Metric label="Return" value={`${((value/100000-1)*100).toFixed(2)}%`} sub="Current simulation" positive={value>=100000}/><Metric label="Trades" value={String(trades.length)} sub="Paper executions"/></div><div className="section-grid"><Panel title="POSITION ALLOCATION"><Allocation positions={positions}/></Panel><Panel title="RISK SNAPSHOT"><Risk/></Panel></div><Panel title="EXECUTION HISTORY"><JournalTable trades={trades}/></Panel></>}
function Intelligence({news,market}:{news:NewsItem[];market:Record<string,{price:number;change:number}>}){return <><div className="intel-grid">{news.map(n=><article className="news" key={n.id}><div className="news-top"><b>{n.symbol}</b><span>{timeAgo(n.publishedAt)}</span></div><h3>{n.title}</h3><div className="news-bottom"><span>{n.source}</span><a href={n.url} target="_blank" rel="noreferrer">OPEN SOURCE ↗</a></div></article>)}</div><div className="section-grid"><Panel title="LIVE MARKET SNAPSHOT"><div className="evidence">{Object.entries(market).map(([s,m])=><Bar key={s} label={`${s} · $${m.price.toLocaleString()}`} value={Math.min(100,Math.abs(m.change)*15+50)}/>)}</div></Panel><Panel title="EVIDENCE SYNTHESIS"><div className="evidence"><Bar label="News sentiment" value={74}/><Bar label="Price momentum" value={67}/><Bar label="Fundamentals" value={81}/><Bar label="Macro" value={42}/><Bar label="Risk" value={31}/></div></Panel></div></>}
function Training({train,training,lessons,modelVersion}:{train:()=>void;training:boolean;lessons:number;modelVersion:number}){return <><div className="training-hero"><div><span className="eyebrow violet">MODEL DEVELOPMENT</span><h2>Training Lab</h2><p>Evaluate completed predictions, record mistakes, and create a candidate model. This is research training—not a claim of guaranteed profitability.</p></div><button className="primary" onClick={train}>{training?"TRAINING…":"RUN TRAINING SESSION"}</button></div><div className="metrics"><Metric label="Current model" value={`v${modelVersion}`} sub="Adaptive baseline"/><Metric label="Accuracy" value="63.4%" sub="Walk-forward metric"/><Metric label="Lessons" value={String(lessons)} sub="Post-mortems"/><Metric label="MAE" value="2.7%" sub="Mean absolute error"/></div><div className="model-timeline">{[54,57,61,63,67].map((v,i)=><div key={v} className={i===4?'current':''}><span>v{i+1}</span><i style={{height:`${v}%`}}/><b>{v}%</b></div>)}</div><Panel title="LATEST LESSON"><div className="lesson"><b>LESSON #{lessons}</b><h3>Sentiment needs regime awareness</h3><p>Post-mortems can identify feature interactions that should be tested on unseen data before model promotion.</p><span>→ candidate feature interaction</span></div></Panel></>}
function Journal({trades}:{trades:Trade[]}){return <Panel title="PAPER TRADE JOURNAL" meta="LOCAL AUDIT LOG"><JournalTable trades={trades}/></Panel>}
function JournalTable({trades}:{trades:Trade[]}){return <div className="journal-table">{trades.length===0?<div className="empty">No paper executions yet. Use a decision's PAPER button.</div>:trades.map((t,i)=><div className="jrow" key={i}><b>{t.symbol}</b><span className={`signal ${t.action.toLowerCase()}`}>{t.action}</span><span>{t.qty} unit</span><span>${t.price.toLocaleString()}</span><span>{t.time}</span><em>FILLED</em></div>)}</div>}
function Metric({label,value,sub,positive=false}:{label:string;value:string;sub:string;positive?:boolean}){return <div className="metric"><span>{label}</span><strong className={positive?"positive":""}>{value}</strong><small>{sub}</small></div>}
function Panel({title,meta,children}:{title:string;meta?:string;children:React.ReactNode}){return <section className="panel"><div className="panel-head"><span>{title}</span><em>{meta}</em></div>{children}</section>}
function Equity(){const pts=[24,31,29,42,38,49,46,58,54,66,61,72,69,81,78,91];return <div className="equity"><svg viewBox="0 0 800 240" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#8b7cff" stopOpacity=".32"/><stop offset="1" stopColor="#8b7cff" stopOpacity="0"/></linearGradient></defs><path d={`M0,220 ${pts.map((p,i)=>`L${i*53},${220-p*2}`).join(" ")} L800,220 Z`} fill="url(#area)"/><polyline points={pts.map((p,i)=>`${i*53},${220-p*2}`).join(" ")} fill="none" stroke="#9a8cff" strokeWidth="3"/></svg><div className="axis"><span>30D AGO</span><span>NOW</span></div></div>}
function Allocation({positions}:{positions:Record<string,number>}){const total=Object.values(positions).reduce((a,b)=>a+b,0);let start=0;const colors=['#9a8cff','#61e7c8','#65b9ff','#ff9c6b'];const stops=Object.entries(positions).map(([_,v],i)=>{const a=start;start+=v;return `${colors[i%4]} ${a}% ${start}%`}).join(', ');return <div className="allocation"><div className="donut" style={{background:`conic-gradient(${stops}, #222936 0)`}}><div>{total}%</div></div><div className="legend">{Object.entries(positions).map(([k,v],i)=><div key={k}><i style={{background:colors[i%4]}}/><b>{k}</b><span>{v}%</span></div>)}</div></div>}
function Risk(){return <div className="risk"><Bar label="Portfolio volatility" value={38}/><Bar label="Concentration" value={44}/><Bar label="Model uncertainty" value={29}/><Bar label="Liquidity risk" value={18}/><p>Paper-only risk controls. No real-money broker is connected.</p></div>}
function Bar({label,value}:{label:string;value:number}){return <div className="barline"><div><span>{label}</span><b>{value}%</b></div><i><em style={{width:`${value}%`}}/></i></div>}
function timeAgo(date:string){const m=Math.max(0,Math.floor((Date.now()-Date.parse(date))/60000));return m<1?"now":m<60?`${m}m ago`:`${Math.floor(m/60)}h ago`}
